package org.aksw.jena.rdfpatch.stream;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;

import com.google.common.collect.AbstractIterator;
import com.google.common.collect.Iterators;
import com.google.common.collect.PeekingIterator;

import org.aksw.jena.rdfpatch.stream.PatchRecord.Type;
import org.apache.jena.atlas.iterator.Iter;
import org.apache.jena.atlas.iterator.IteratorCloseable;

/**
 * Iterator that applies one or more sorted patch streams (ADD/DELETE) on top of a sorted base iterator.
 * All inputs must be sorted using the same ordering defined by the supplied comparator.
 */
// Generated by Grok 2026-04-01
public class PatchApplyIterator<T>
    extends AbstractIterator<T>
    implements IteratorCloseable<T> {

    private final Comparator<? super T> comparator;
    private final PeekingIterator<T> baseIter;
    private final List<PeekingIterator<PatchRecord<T>>> patchIters;

    // For closing.
    private final List<? extends Iterator<PatchRecord<T>>> patches;

    /**
     * @param base          Sorted base iterator
     * @param patches       List of patch iterators (each containing ADD/DELETE entries), also sorted
     * @param comparator    Comparator defining the sort order of T
     */
    public PatchApplyIterator(Iterator<T> base,
                              List<? extends Iterator<PatchRecord<T>>> patches,
                              Comparator<? super T> comparator) {
        this.comparator = Objects.requireNonNull(comparator);
        this.baseIter = Iterators.peekingIterator(Objects.requireNonNull(base));

        this.patches = patches;

        this.patchIters = new ArrayList<>(patches.size());
        for (Iterator<PatchRecord<T>> patch : patches) {
            this.patchIters.add(Iterators.peekingIterator(patch));
        }
    }

    @Override
    protected T computeNext() {
        while (true) {
            // Find the smallest candidate key among base and all patches
            T candidate = null;

            // Check base
            if (baseIter.hasNext()) {
                candidate = baseIter.peek();
            }

            // Check all patches for smaller (or equal) keys
            for (PeekingIterator<PatchRecord<T>> patch : patchIters) {
                if (patch.hasNext()) {
                    T patchKey = patch.peek().value();
                    int cmp = -666;
                    if (candidate == null || (cmp = comparator.compare(patchKey, candidate)) < 0) {
                        candidate = patchKey;
                    }
                    // System.out.println(patchKey + " " + candidate + ": " + cmp);
                }
            }

            if (candidate == null) {
                return endOfData(); // everything exhausted
            }

            // Now process this candidate key: apply all patches for this exact key (in patch order)
            boolean shouldEmit = true;

            // First, check if base has this exact key
            if (baseIter.hasNext() && comparator.compare(baseIter.peek(), candidate) == 0) {
                shouldEmit = true; // tentatively emit unless deleted
            } else {
                shouldEmit = false; // no base entry → only emit if explicitly added
            }

            // Apply patches in order (later patches override earlier ones)
            for (PeekingIterator<PatchRecord<T>> patch : patchIters) {
                if (patch.hasNext() && comparator.compare(patch.peek().value(), candidate) == 0) {
                    PatchRecord<T> entry = patch.next(); // consume it

                    if (entry.type() == Type.DELETED) {
                        shouldEmit = false;
                    } else if (entry.type() == Type.ADDED) {
                        shouldEmit = true;
                    }
                }
            }

            // Advance base if it matched the candidate
            if (baseIter.hasNext() && comparator.compare(baseIter.peek(), candidate) == 0) {
                baseIter.next(); // consume base entry
            }

            if (shouldEmit) {
                return candidate;
            }

            // If we suppressed it, continue to find the next valid triple
        }
    }

    @Override
    public void close() {
        Iter.close(baseIter);
        // XXX Perhaps use try-catch to recover from exception during close.
        patches.forEach(Iter::close);
    }
}
